imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: ["!security"]
            exclude_404s:
                - ^/frame
        security:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.security.log
            level: warning
            channels: ["security"]
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
