imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

wikp_payment_mtgox:
    api_key: %mtgox_api_key%
    api_secret: %mtgox_api_secret%
    return_url: http://dupa.com/
    cancel_url: http://dupa.com/
    order_repository_path: "HyperAdsBundle:Order"
    debug: %kernel.debug%

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        handler_id: session.handler.memcache

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            bannertype: Hyper\AdsBundle\DBAL\BannerType
            zonetype: Hyper\AdsBundle\DBAL\ZoneType
            announcement_payment_type: Hyper\AdsBundle\DBAL\AnnouncementPaymentType
            paymodeltype: Hyper\AdsBundle\DBAL\PayModelType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Hyper\AdsBundle\Entity\Advertiser
    from_email:
        address: %mailer_from%
        sender_name: %mailer_sender%
    registration:
        confirmation:
            enabled: true

jms_payment_core:
    secret: %payments_secret%


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

services:
    session.memcache:
        class: Memcache
        calls:
            - [ addServer, [ %session_memcache_host%, %session_memcache_port% ]]

    session.handler.memcache:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcacheSessionHandler
        arguments: [ @session.memcache, { prefix: %session_memcache_prefix%, expiretime: %session_memcache_expire% } ]
