parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     albert
    database_user:     hofmann
    database_password: bicycle1943

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~
    mailer_delivery:   me@example.com
    mailer_from:       me@example.com
    mailer_sender:     me@example.com

    payments_secret:  som3S3cr37P4ssw0rd
    mtgox_api_key:    apiKey
    mtgox_api_secret: "apiSecret"

    ads_default_currency: EUR
    page_title: "acid.ad.server"

    locale:            pl
    secret:            0724ebb222af8866b7d7a2524451219b

    session_memcache_host: 127.0.0.1
    session_memcache_port: 11211
    session_memcache_prefix: "acid_"
    session_memcache_expire: 3600

    application_memcache_host: 127.0.0.1
    application_memcache_port: 11211
    application_memcache_prefix: "acid_"

    max_one_banner_days: 365

    announcement_flow_mail_recipients:
        - "mail@example.com"
        - "another-mail@example.com"