parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     albert
    database_user:     hofmann
    database_password: bicycle1943

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            pl
    secret:            0724ebb222af8866b7d7a2524451219b
