wikp_payment_mtgox:
    resource: "@WikpPaymentMtgoxBundle/Resources/config/routing.yml"
    prefix:   /mtgox

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_welcome:
    pattern:  /
    defaults: { _controller: HyperAdsBundle:Default:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

default:
    resource: "@HyperAdsBundle/Controller/DefaultController.php"
    type: annotation

admin_advertiser:
    resource: "@HyperAdsBundle/Controller/AdvertiserController.php"
    prefix: /admin/advertiser
    type: annotation

admin_page:
    resource: "@HyperAdsBundle/Controller/PageController.php"
    prefix: /admin/page
    type: annotation

admin_zone:
    resource: "@HyperAdsBundle/Controller/ZoneController.php"
    prefix: /admin/zone
    type: annotation

admin_banner_config:
    resource: "@HyperAdsBundle/Controller/BannerConfigController.php"
    prefix: /admin/banner-config
    type: annotation

admin_banner:
    resource: "@HyperAdsBundle/Controller/BannerController.php"
    prefix: /admin/banner
    type: annotation

user_banner:
    resource: "@HyperAdsBundle/Controller/UserBannerController.php"
    prefix: /user/banner
    type: annotation

user_announcement:
    resource: "@HyperAdsBundle/Controller/UserAnnouncementController.php"
    prefix: /user/announcement
    type: annotation

acid_api:
    resource: "@HyperAdsBundle/Controller/ApiController.php"
    prefix: /api
    type: annotation

payments:
    resource: "@HyperAdsBundle/Controller/PaymentsController.php"
    prefix: /payments
    type: annotation
