# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_welcome:
    pattern:  /
    defaults: { _controller: HyperAdsBundle:Default:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin_advertiser:
    resource: "@HyperAdsBundle/Controller/AdvertiserController.php"
    prefix: /admin/advertiser
    type: annotation

admin_page:
    resource: "@HyperAdsBundle/Controller/PageController.php"
    prefix: /admin/page
    type: annotation

admin_campaign:
    resource: "@HyperAdsBundle/Controller/CampaignController.php"
    prefix: /admin/campaign
    type: annotation

admin_zone:
    resource: "@HyperAdsBundle/Controller/ZoneController.php"
    prefix: /admin/zone
    type: annotation

admin_banner:
    resource: "@HyperAdsBundle/Controller/BannerController.php"
    prefix: /admin/banner
    type: annotation
